# DBT profiles for podcast analytics pipeline
# Note: This file uses environment variables for sensitive values
# In production, credentials are injected via 1Password operator

podcast_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_POSTGRES_USER', 'postgres') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', '') }}"
      dbname: "{{ env_var('DBT_POSTGRES_DATABASE', 'eleduck') }}"
      schema: raw
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', '5432') | int }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('DBT_POSTGRES_DATABASE') }}"
      schema: raw
      threads: 8
