apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eleduck-analytics

resources:
  - namespace.yaml
  # 1Password secrets
  - 1password/onepassworditem-postgres.yaml
  - 1password/onepassworditem-spotify.yaml
  - 1password/onepassworditem-youtube.yaml
  # Database
  - postgres/
  # Data pipeline
  - airbyte/
  # Analytics dashboard
  - metabase/
