apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eleduck-analytics

resources:
  - namespace.yaml
  # 1Password items
  - 1password/onepassworditem-postgres.yaml
  - 1password/onepassworditem-metabase.yaml
  # Infrastructure
  - postgres/
  - metabase/
